# NO SE INGLÉS Y LE HE ROBADO EL CÓDIGO AL PSYCH XDDD
# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
           haxelib install haxeui-core
           haxelib install haxeui-hxwidgets
           haxelib install hxcpp
           haxelib install openfl
           haxelib install hxcpp-debug-server
           haxelib install flixel
           haxelib run lime setup flixel
          haxelib install flixel-tools
          haxelib git systools https://github.com/haya3218/systools
          haxelib run lime rebuild systools windows
          haxelib run flixel-tools setup
          haxelib install flixel-addons
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install flixel-ui
          haxelib install linc_luajit
          haxelib git tentools https://github.com/TentaRJ/tentools
           haxelib install lime
           haxelib run lime setup
           haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows -32 --app-version="1.5-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Build1
          path: crash-dialog/build/windows/Main.exe
